### PR TITLE
fix the Color Of the button to red and add the plus icone

### PR DESCRIPTION
**Pull request by styrexx**
#71 Fix this issue and add the plus icon

### CODE REVIEW

**Comment by styrexx** [comment]
@soufyanelf  I am waiting for you to review the code 👍🏼

**Comment by soufyanelf** [comment]
The UI still not following the mockup 
image

**Comment by soufyanelf** [comment]
> The UI still not following the mockup image

@styrexx

**Comment by styrexx** [comment]
@soufyanelf  I want to know if this style is allowed for computer screen

**Comment by soufyanelf** [comment]
@styrexx for the web the btn need to be on the left
image

**Comment by styrexx** [comment]
@soufyanelf  I think what you need is Done 👍🏼  

> @styrexx for the web the btn need to be on the left image

**Comment by soufyanelf** [comment]
I want to merge this PR but there is a merge conflict

**Comment by soufyanelf** [comment]
I'm going to close this PR

**Pull request closed without merging**
