### PR TITLE
Migrate to tailwind css

### PR DESCRIPTION
**Pull request by abdellatif-laghjaj**
Hello
I've changed the UI of the web app, I used **tailwind CSS** and **daisy UI** 

_**Note: Thanks in advance for the web app, It's really a good idea :)**_

- **Home page**

image

- **Details page**

image

### CODE REVIEW

**Comment by soufyanelf** [comment]
is there a reason why we may move from mui to tailwind?

**Comment by abdellatif-laghjaj** [comment]
No, I just find Tailwind cleaner than Mui

**Comment by Everkers** [comment]
> No, I just find Tailwind cleaner than Mui
I invite you to join the discord the server to stay updated with other collaborators.

**Comment by soufyanelf** [comment]
Let's hold this move for now and we focus on the features.

**Comment by abdellatif-laghjaj** [comment]
Okay, guys!

**Comment by soufyanelf** [comment]
can we close this one for now and we make a discussion about adding  tailwind CSS you can pick an issue as well.
please join the discord channel if you are not in: https://discord.com/invite/pjyW6Zje

**Comment by abdellatif-laghjaj** [comment]
Done, i join it

**Pull request closed without merging**
